Task 3: Feature Engineering

Extract additional features from the existing
columns, such as the length of the restaurant
name or address.

Create new features like "Has Table Booking"
or "Has Online Delivery" by encoding
categorical variables.

In [7]:
import pandas as pd
df = pd.read_csv("Dataset .csv")
df

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [17]:
df['Name Length'] = df['Restaurant Name'].apply(lambda x: len(str(x)))
df['Name Length']

0       2
1       2
2       2
3       1
4       2
       ..
9546    2
9547    2
9548    1
9549    2
9550    2
Name: Name Length, Length: 9551, dtype: int64

In [15]:
df['Name Length'] = df['Address'].apply(lambda x: len(str(x)))

In [16]:
df['Name Word Count'] = df['Restaurant Name'].apply(lambda x: len(str(x).split()))
df['Address Word Count'] = df['Address'].apply(lambda x: len(str(x).split()))

In [18]:
df[['Restaurant Name', 'Name Length', 'Name Word Count']].head()
df[['Address', 'Address Length', 'Address Word Count']].head()

,Address,Address Length,Address Word Count
0,"Third Floor, Century City Mall, Kalayaan Avenu...",71,10
1,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...",67,10
2,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...",56,8
3,"Third Floor, Mega Fashion Hall, SM Megamall, O...",70,10
4,"Third Floor, Mega Atrium, SM Megamall, Ortigas...",64,9

In [19]:
df['Has_Table_Booking_Encoded'] = df['Has Table booking'].map({'Yes': 1, 'No': 0})

In [20]:
df['Has_Online_Delivery_Encoded'] = df['Has Online delivery'].map({'Yes': 1, 'No': 0})

In [21]:
df['Is_Delivering_Now_Encoded'] = df['Is delivering now'].map({'Yes': 1, 'No': 0})
df['Switch_to_Order_Menu_Encoded'] = df['Switch to order menu'].map({'Yes': 1, 'No': 0})

In [22]:
df[['Has Table booking', 'Has_Table_Booking_Encoded',
    'Has Online delivery', 'Has_Online_Delivery_Encoded']].head()

,Has Table booking,Has_Table_Booking_Encoded,Has Online delivery,Has_Online_Delivery_Encoded
0,Yes,1,No,0
1,Yes,1,No,0
2,Yes,1,No,0
3,No,0,No,0
4,Yes,1,No,0

In [23]:
df.to_csv('encoded_restaurant_data.csv', index=False)